### PR TITLE
Bug/233/promise deletion with orphaned resources

### LINKED ISSUE #233: bug: promise can't be deleted when there are orphaned resources
_relates to #232_

## Steps to reproduce

* Run Kratix quick-start
* Install the Redis promise from the marketplace
* Request a new instance from the promise
* Ensure the redis operator and the requested redis are running in the worker
* In the platform, delete the worker-1 destination
* Delete the redis promise

### Expected
* The Redis instance gets deleted
* The Redis Promise gets deleted

### Actual
* Redis Promise never gets deleted
* Redis resource never gets deleted
* Kratix Controller gets into a reconciliation loop

### PR DESCRIPTION
**Pull request by SaphMB**
* Run Kratix quick-start
* Install the Redis promise from the marketplace
* Request a new instance from the promise
* Ensure the redis operator and the requested redis are running in the worker
* In the platform, delete the worker-1 destination
* Delete the redis promise

### New Behaviour
* The Redis instance gets deleted
* The Redis Promise gets deleted

Closes #233

### CODE REVIEW

File: controllers/workplacement_controller.go [hunk 1]
```diff
@@ -80,19 +77,46 @@ func (r *WorkPlacementReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
-	}
 
 	opts := opts{
 		client: r.Client,
 		ctx:    ctx,
 		logger: logger,
 	}
 
-	//Mock this out
+	err = r.Client.Get(context.Background(), destinationName, destination)
```
Comment (ChunyiLyu) [inline controllers/workplacement_controller.go:87]:
```suggestion
	err = r.Client.Get(ctx, destinationName, destination)
```
we should use the provided context

File: controllers/workplacement_controller.go [hunk 2]
```diff
@@ -80,19 +77,46 @@ func (r *WorkPlacementReconciler) Reconcile(ctx context.Context, req ctrl.Reques
...
+		var writer writers.StateStoreWriter
+		if destinationExists {
+			filepathMode = destination.GetFilepathMode()
+			writer, err = newWriter(opts, *destination)
+			if err != nil {
+				return requeueIfNotFound(err)
+			}
+		}
+
+		return r.deleteWorkPlacement(ctx, destinationExists, writer, workPlacement, filepathMode, logger)
```
Comment (ChunyiLyu) [inline controllers/workplacement_controller.go:111]: May I suggest moving this part to a helper `handleDeletion()`? This is making existing reconciliation quite verbose

**Review by ChunyiLyu — APPROVED** [review]
🚀

File: controllers/workplacement_controller.go (hunk 2 above)
Comment (SaphMB) [reply controllers/workplacement_controller.go]: Good suggestion - done
